development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: iuran_development
  pool: 5
  username: postgres
  password: postgres

staging:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: iuran_staging
  pool: 5 
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: iuran_production
  pool: 5 
  username: postgres
  password: postgres